"""Modify symptoms and signs to link to patients, add severity

Revision ID: fa995c59f832
Revises: 31723287ba35
Create Date: 2026-07-04 02:07:59.226790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fa995c59f832'
down_revision: Union[str, Sequence[str], None] = '31723287ba35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pentacam_tests', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pentacam_tests', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('pentacam_tests', 'eye',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pentacam_values', 'pentacam_test_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('pentacam_values', 'key',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pentacam_values', 'value',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('signs', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.add_column('signs', sa.Column('severity', sa.String(), nullable=False))
    op.alter_column('signs', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_constraint(op.f('signs_visit_id_fkey'), 'signs', type_='foreignkey')
    op.create_foreign_key(None, 'signs', 'patients', ['patient_id'], ['id'])
    op.drop_column('signs', 'visit_id')
    op.add_column('symptoms', sa.Column('patient_id', sa.Integer(), nullable=False))
    op.add_column('symptoms', sa.Column('severity', sa.String(), nullable=False))
    op.alter_column('symptoms', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.drop_constraint(op.f('symptoms_visit_id_fkey'), 'symptoms', type_='foreignkey')
    op.create_foreign_key(None, 'symptoms', 'patients', ['patient_id'], ['id'])
    op.drop_column('symptoms', 'visit_id')
    op.alter_column('vision_tests', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('vision_tests', 'eye',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('vision_tests', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('visits', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('visits', 'notes',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('visits', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('visits', 'patient_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('vision_tests', 'notes',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('vision_tests', 'eye',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('vision_tests', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('symptoms', sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'symptoms', type_='foreignkey')
    op.create_foreign_key(op.f('symptoms_visit_id_fkey'), 'symptoms', 'visits', ['visit_id'], ['id'])
    op.alter_column('symptoms', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('symptoms', 'severity')
    op.drop_column('symptoms', 'patient_id')
    op.add_column('signs', sa.Column('visit_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'signs', type_='foreignkey')
    op.create_foreign_key(op.f('signs_visit_id_fkey'), 'signs', 'visits', ['visit_id'], ['id'])
    op.alter_column('signs', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('signs', 'severity')
    op.drop_column('signs', 'patient_id')
    op.alter_column('pentacam_values', 'value',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pentacam_values', 'key',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pentacam_values', 'pentacam_test_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pentacam_tests', 'eye',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pentacam_tests', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('pentacam_tests', 'visit_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
